version: '3.4'
services:

  # celery worker
  worker:
    image: data61/anonlink-app:${TAG:-latest}
    command: celery -A entityservice.async_worker worker --loglevel=info -O fair -Q celery,compute,highmemory
    env_file:
      - .env
    environment:
      - CELERY_ACKS_LATE=true
      - REDIS_USE_SENTINEL=false
      - CELERYD_MAX_TASKS_PER_CHILD=2048
      #- CHUNK_SIZE_AIM=300_000_000
      - CELERY_DB_MIN_CONNECTIONS=1
      - CELERY_DB_MAX_CONNECTIONS=3



